const paymentPrepaid = {
  "count": 6,
  "data": [
      {
          "roomName": "room_office",
          "paid": 0,
          "reserveId": 251,
          "memberId": 1,
          "rooomId": 1,
          "bookDate": {
              "reserveDate": "2022-11-24T14:40:40",
              "cancelDate": null,
              "checkInDate": "2022-11-30",
              "checkOutDate": "2022-12-30",
              "checkInTime": 9,
              "checkOutTime": 14,
          },
          "name": "사용자",
          "reserveStatus": "BOOKED",
          "paymentStatus": "POSTPAID",
          "roomType": "OFFICE",
          "reserveAmount": 300000,
      },
      {
        "roomName": "room_office",
        "paid": 0,
        "reserveId": 251,
        "memberId": 1,
        "rooomId": 1,
        "bookDate": {
            "reserveDate": "2022-11-24T14:40:40",
            "cancelDate": null,
            "checkInDate": "2022-11-30",
            "checkOutDate": "2022-12-30",
            "checkInTime": 9,
            "checkOutTime": 14,
        },
        "name": "사용자",
        "reserveStatus": "BOOKED",
        "paymentStatus": "POSTPAID",
        "roomType": "OFFICE",
        "reserveAmount": 300000,
    },
    {
      "roomName": "room_office",
      "paid": 0,
      "reserveId": 251,
      "memberId": 1,
      "rooomId": 1,
      "bookDate": {
          "reserveDate": "2022-11-24T14:40:40",
          "cancelDate": null,
          "checkInDate": "2022-11-30",
          "checkOutDate": "2022-12-30",
          "checkInTime": 9,
          "checkOutTime": 14,
      },
      "name": "사용자",
      "reserveStatus": "BOOKED",
      "paymentStatus": "POSTPAID",
      "roomType": "OFFICE",
      "reserveAmount": 300000,
  },
  {
    "roomName": "room_office",
    "paid": 0,
    "reserveId": 251,
    "memberId": 1,
    "rooomId": 1,
    "bookDate": {
        "reserveDate": "2022-11-24T14:40:40",
        "cancelDate": null,
        "checkInDate": "2022-11-30",
        "checkOutDate": "2022-12-30",
        "checkInTime": 9,
        "checkOutTime": 14,
    },
    "name": "사용자",
    "reserveStatus": "BOOKED",
    "paymentStatus": "POSTPAID",
    "roomType": "OFFICE",
    "reserveAmount": 300000,
},
{
  "roomName": "room_office",
  "paid": 0,
  "reserveId": 251,
  "memberId": 1,
  "rooomId": 1,
  "bookDate": {
      "reserveDate": "2022-11-24T14:40:40",
      "cancelDate": null,
      "checkInDate": "2022-11-30",
      "checkOutDate": "2022-12-30",
      "checkInTime": 9,
      "checkOutTime": 14,
  },
  "name": "사용자",
  "reserveStatus": "BOOKED",
  "paymentStatus": "POSTPAID",
  "roomType": "OFFICE",
  "reserveAmount": 300000,
},
      {
          "roomName": "room_desk",
          "paid": 0,
          "reserveId": 201,
          "memberId": 1,
          "rooomId": 51,
          "bookDate": {
              "reserveDate": "2022-11-24T13:30:30",
              "cancelDate": null,
              "checkInDate": "2022-12-30",
              "checkOutDate": "2022-12-30",
              "checkInTime": 9,
              "checkOutTime": 14,
          },
          "name": "사용자",
          "reserveStatus": "BOOKED",
          "paymentStatus": "PREPAID",
          "roomType": "DESK",
          "reserveAmount": 50000,
      },
      {
          "roomName": "room_office",
          "paid": 1,
          "reserveId": 151,
          "memberId": 1,
          "rooomId": 1,
          "bookDate": {
              "reserveDate": "2022-11-24T13:30:30",
              "cancelDate": null,
              "checkInDate": "2022-12-27",
              "checkOutDate": "2022-12-27",
              "checkInTime": 21,
              "checkOutTime": 23,
          },
          "name": "사용자",
          "reserveStatus": "BOOKED",
          "paymentStatus": "PREPAID",
          "roomType": "OFFICE",
          "reserveAmount": 30000,
      },
      {
          "roomName": "room_desk",
          "paid": 0,
          "reserveId": 101,
          "memberId": 1,
          "rooomId": 51,
          "bookDate": {
              "reserveDate": "2022-11-24T13:30:30",
              "cancelDate": null,
              "checkInDate": "2022-12-27",
              "checkOutDate": "2022-12-27",
              "checkInTime": 21,
              "checkOutTime": 23,
          },
          "name": "사용자",
          "reserveStatus": "BOOKED",
          "paymentStatus": "PREPAID",
          "roomType": "DESK",
          "reserveAmount": 30000,
      },
      {
          "roomName": "room_desk",
          "paid": 0,
          "reserveId": 51,
          "memberId": 1,
          "rooomId": 51,
          "bookDate": {
              "reserveDate": "2022-11-24T13:30:30",
              "cancelDate": null,
              "checkInDate": "2022-12-23",
              "checkOutDate": "2022-12-23",
              "checkInTime": 20,
              "checkOutTime": 23,
          },
          "name": "사용자",
          "reserveStatus": "NOSHOW",
          "paymentStatus": "PREPAID",
          "roomType": "DESK",
          "reserveAmount": 30000,
      },
      {
          "roomName": "room_desk",
          "paid": 0,
          "reserveId": 1,
          "memberId": 1,
          "rooomId": 51,
          "bookDate": {
              "reserveDate": "2022-11-24T13:30:30",
              "cancelDate": null,
              "checkInDate": "2022-12-22",
              "checkOutDate": "2022-12-22",
              "checkInTime": 20,
              "checkOutTime": 23,
          },
          "name": "사용자",
          "reserveStatus": "NOSHOW",
          "paymentStatus": "PREPAID",
          "roomType": "DESK",
          "reserveAmount": 30000,
      },
  ],
}

const paymentSchedule = {
  "code": 0,
  "message": null,
  "response": [
      {
          "customer_uid": "customer_uid8",
          "merchant_uid": "order_postpaid_0029예약결제",
          "imp_uid": null,
          "schedule_at": "2022-12-03T07:41:29.000+00:00",
          "executed_at": null,
          "revoked_at": null,
          "amount": 16000,
          "name": null,
          "buyer_name": null,
          "buyer_email": null,
          "buyer_tel": null,
          "buyer_addr": null,
          "buyer_postcode": null,
          "custom_data": null,
          "schedule_status": null,
          "payment_status": null,
          "fail_reason": null,
          "customerUid": "customer_uid8",
          "merchantUid": "order_postpaid_0029예약결제",
          "scheduleAt": "2022-12-03T07:41:29.000+00:00",
      },
  ],
}

const mileage = {
  "count": 3700,
  "data": [
      {
          "mileageId": 201,
          "roomName": "room_desk",
          "payId": 101,
          "status": "SAVED",
          "mileageAmount": 3000,
          "mileageDate": "2022-12-04",
      },
      {
          "mileageId": 251,
          "roomName": "room_desk",
          "payId": 101,
          "status": "USED",
          "mileageAmount": 300,
          "mileageDate": "2022-12-04",
      },
      {
          "mileageId": 101,
          "roomName": "room_desk",
          "payId": 51,
          "status": "SAVED",
          "mileageAmount": 2000,
          "mileageDate": "2022-12-04",
      },
      {
          "mileageId": 151,
          "roomName": "room_desk",
          "payId": 51,
          "status": "USED",
          "mileageAmount": 1500,
          "mileageDate": "2022-12-04",
      },
      {
          "mileageId": 1,
          "roomName": "room_desk",
          "payId": 1,
          "status": "SAVED",
          "mileageAmount": 1000,
          "mileageDate": "2022-12-02",
      },
      {
          "mileageId": 51,
          "roomName": "room_desk",
          "payId": 1,
          "status": "USED",
          "mileageAmount": 500,
          "mileageDate": "2022-12-02",
      },
  ],
}

// 결제정산
const payment = {
  "count": 3,
  "data": [
      {
          "reserveDate": "2022-11-24T13:30:30",
          "name": "사용자",
          "spaceName": "space_desk",
          "roomName": "room_desk",
          "reserveAmount": 300000,
          "payAmount": 1004,
          "payStatus": "POSTPAID_BOOKED",
          "reserveStatus": "NOSHOW",
          "tel": "1111-1111",
      },
      {
          "reserveDate": "2022-11-24T13:30:30",
          "name": "사용자",
          "spaceName": "space_desk",
          "roomName": "room_desk",
          "reserveAmount": 300000,
          "payAmount": 1004,
          "payStatus": "DEPOSIT",
          "reserveStatus": "NOSHOW",
          "tel": "1111-1111",
      },
      {
          "reserveDate": "2022-11-24T13:30:30",
          "name": "사용자",
          "spaceName": "space_desk",
          "roomName": "room_desk",
          "reserveAmount": 300000,
          "payAmount": 300000,
          "payStatus": "PREPAID",
          "reserveStatus": "BOOKED",
          "tel": "1111-1111",
      },
  ],
}

export {
  paymentPrepaid,
  paymentSchedule,
  mileage,
  payment,
}