const QnAdummy = [
  {
      "qnaId": 1,
      "spaceId": 3,
      "spaceName": '공간1호',
      "memberId": 4,
      "type": "RESERVE",
      "content": "냉무",
      "lastModifiedDate": "2022-11-28T17:29:59.875",
      "qnacomment": null,
      "qclastModifiedDate": null,
  },
  {
      "qnaId": 2,
      "spaceId": 3,
      "spaceName": '공간2호',
      "memberId": 4,
      "type": "PAY",
      "content": "testtet",
      "lastModifiedDate": "2022-10-20T17:29:59.875",
      "qnacomment": "답글임니다",
      "qclastModifiedDate": "2022-11-29T15:55:26.411",
  },
  {
      "qnaId": 3,
      "spaceId": 1,
      "spaceName": '공간3호',
      "memberId": 4,
      "type": "USING",
      "content": "sdfsdsdsㄴ하ㅣㅓㅎㄹㄴ몮리",
      "lastModifiedDate": "2022-11-29T17:42:46.476384",
      "qnacomment": null,
      "qclastModifiedDate": null,
  },
]

const ReviewDummy = [
  {
    "spacetype":'DESK',
    "spaceName": '공간1호',
    "roomName": '방1번',
    "reviewId": 1,
    "reservationId": 1,
    "memberId": 4,
    "content": "춫ㄴ합니다",
    "lastModifiedDate": "2022-11-30T12:35:52.247",
    "grade": 4,
  },
  {
    "spacetype":'OFFICE',
    "spaceName": '공간1호',
    "roomName": '방2번',
    "reviewId": 2,
    "reservationId": 1,
    "memberId": 4,
    "content": "춫ㄴ합니다",
    "lastModifiedDate": "2022-11-30T13:29:01.177478",
    "grade": 3,
  },
  {
    "spacetype":'MEETING8',
    "spaceName": '공간1호',
    "roomName": '방3번',
    "reviewId": 3,
    "reservationId": 1,
    "memberId": 4,
    "content": "춫ㄴ합니다",
    "lastModifiedDate": "2022-11-30T13:29:01.177478",
    "grade": 2,
  },
]

export {
  QnAdummy,
  ReviewDummy,
}