const spaceDumy = [
  {
    spaceName:"더미 공간 1호",
    spaceImg : "dummy1.jpg",
    address:"경기도 수원시 장안구",
    spaceId:"1",
    grade:"4",
    review:"100",
    spaceStatus: "roomSetting",
    spaceType:'1',
  },
  {
    spaceName:"더미 공간 2호",
    spaceImg : "dummy2.jpg",
    address:"경기도 수원시 장안구",
    spaceId:"2",
    grade:"3",
    review:"100",
    spaceStatus: "approved",
    spaceType:'2',
  },
  {
    spaceName:"더미 공간 3호",
    spaceImg : "dummy3.jpg",
    address:"경기도 수원시 장안구",
    spaceId:"3",
    grade:"1",
    review:"100",
    spaceStatus: "roomSetting",
    spaceType:'1',
  },
  {
    spaceName:"더미 공간 4호",
    spaceImg : "dummy1.jpg",
    address:"경기도 수원시 장안구",
    spaceId:"4",
    grade:"5",
    review:"100",
    spaceStatus: "approved",
    spaceType:'2',
  },
  {
    spaceName:"더미 공간 5호",
    spaceImg : "dummy2.jpg",
    address:"경기도 수원시 장안구",
    spaceId:"5",
    grade:"2",
    review:"100",
    spaceStatus: "waiting",
    spaceType:'3',
  },
]

const selectOneSpaceDumy = [
  {
    spaceName:"더미 공간 5호",
    spaceImg : "dummy3.jpg",
    address:"서울특별시 강남구 영동대로",
    detailAddress:"735 골프존타워서울",
    spaceDetail: "더미 공간 1호 입니다.",
    spaceId:"5",
    grade:"2",
    review:"100",
    spaceStatus: "waiting",
    spaceType:'3',
    member: {
      name: '홍길동',
      tel: '010-1234-5678',
      email: 'a@a.com',
    },
  },
]

const selectOneRoomDumy = [
  {
    roomId: '1',
    roomType: 'MEETING4',
    roomName: '기린',
    roomImg: '',
    roomPrice: '20000',
    workStart: '08',
    workEnd:'20',
    roomDetail:'기린이 있는 방',
  },
  {
    roomId: '2',
    roomType: 'MEETING6',
    roomName: '코끼리',
    roomImg: '',
    roomPrice: '20000',
    workStart: '08',
    workEnd:'20',
    roomDetail:'코끼리가 있는 방',
  },
  {
    roomId: '3',
    roomType: 'MEETING8',
    roomName: '낙타',
    roomImg: '',
    roomPrice: '20000',
    workStart: '08',
    workEnd:'20',
    roomDetail:'낙타가 있는 방',
  },
]

export {
  spaceDumy,
  selectOneSpaceDumy,
  selectOneRoomDumy,
}